HEAD http://localhost:8002/result
Host: localhost
Accept: application/json

###
GET http://localhost:8002/func.js
Host: localhost
Accept: application/javascript

###
GET http://localhost:8002/postinfo.html
Host: localhost
Accept: text/html

###
GET http://localhost:8002/style.css
Host: localhost
Accept: text/css

###
GET http://localhost:8002/result
Host: localhost
Content-Type: application/json

###
GET http://localhost:8002/sheet.pdf
Host: localhost
Accept: application/pdf

###
GET http://localhost:8002/cat.png
Host: localhost
Accept: image/png

###
GET http://localhost:8002/inx.html
Host: localhost
Accept: text/html

###
GET http://localhost:8002/index.html
Host: localhost
Accept: text/html

###
HEAD http://localhost:8002/index.html
Host: localhost
Accept: text/html

###
GET http://localhost:8002/number
Host: localhost
Accept: text/html

